// packages/play-vrowzer/fixtures/vite-vue/App.vue
<script setup lang="ts">
import HelloWorld from './HelloWorld.vue'
import vrowzerLogo from './vrowzer.svg'
import vueLogo from './vue.svg'
</script>

<template>
  <div>
    <a href="https://github.com/kazupon/vrowzer" target="_blank">
      <img :src="vrowzerLogo" class="logo" alt="Vrowzer logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img :src="vueLogo" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vrowzer + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// packages/play-vrowzer/fixtures/vite-svelte/App.svelte
<script lang="ts">
  import svelteLogo from './svelte.svg'
  import vrowzerLogo from './vrowzer.svg'
  import Counter from './Counter.svelte'
</script>

<main>
  <div>
    <a href="https://github.com/kazupon/vrowzer" target="_blank" rel="noreferrer">
      <img src={vrowzerLogo} class="logo" alt="Vrowzer Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vrowzer + Svelte</h1>

  <div class="card">
    <Counter />
  </div>

  <p class="read-the-docs">
    Click on the Vrowzer and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>
